# Generated by Django 5.2.9 on 2026-02-21 21:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Axis Camera', max_length=200)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('port', models.IntegerField(default=80)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('stream_url', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('dataset_path', models.CharField(max_length=500)),
                ('images_count', models.IntegerField(default=0)),
                ('labels_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackgroundCalibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calibration_date', models.DateTimeField(auto_now_add=True)),
                ('background_image_path', models.CharField(max_length=500)),
                ('hsv_min_h', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(179)])),
                ('hsv_min_s', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)])),
                ('hsv_min_v', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)])),
                ('hsv_max_h', models.IntegerField(default=179, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(179)])),
                ('hsv_max_s', models.IntegerField(default=255, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)])),
                ('hsv_max_v', models.IntegerField(default=255, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)])),
                ('is_active', models.BooleanField(default=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibrations', to='factory.camera')),
            ],
        ),
        migrations.CreateModel(
            name='DatasetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=500)),
                ('label_path', models.CharField(blank=True, max_length=500, null=True)),
                ('has_label', models.BooleanField(default=False)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='factory.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='ModelTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('base_model', models.CharField(choices=[('yolov8n', 'YOLOv8 Nano'), ('yolov8s', 'YOLOv8 Small'), ('yolov8m', 'YOLOv8 Medium'), ('yolov8l', 'YOLOv8 Large'), ('yolov8x', 'YOLOv8 XLarge')], default='yolov8n', max_length=20)),
                ('epochs', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('batch_size', models.IntegerField(default=16, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(128)])),
                ('image_size', models.IntegerField(default=640, validators=[django.core.validators.MinValueValidator(320), django.core.validators.MaxValueValidator(1280)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('model_path', models.CharField(blank=True, max_length=500, null=True)),
                ('best_model_path', models.CharField(blank=True, max_length=500, null=True)),
                ('training_log_path', models.CharField(blank=True, max_length=500, null=True)),
                ('final_map50', models.FloatField(blank=True, null=True)),
                ('final_map50_95', models.FloatField(blank=True, null=True)),
                ('training_loss', models.FloatField(blank=True, null=True)),
                ('validation_loss', models.FloatField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='factory.dataset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DetectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(blank=True, max_length=500, null=True)),
                ('detection_count', models.IntegerField(default=0)),
                ('confidence_avg', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(default='NO_CANS', max_length=50)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='factory.camera')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detections', to='factory.modeltraining')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
    ]
