# Generated by Django 5.2.9 on 2026-02-22 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='resolution',
            field=models.CharField(blank=True, default='1920x1080', help_text='Rozdzielczość strumienia (używane gdy stream_url jest pusty), np. 1920x1080', max_length=20),
        ),
        migrations.AlterField(
            model_name='camera',
            name='stream_url',
            field=models.CharField(blank=True, help_text='Opcjonalnie: pełny URL MJPEG. Np. http://10.11.59.12/axis-cgi/mjpg/video.cgi?resolution=1920x1080', max_length=500),
        ),
    ]
