# Generated by Django 5.2.9 on 2026-02-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0002_add_camera_resolution_and_stream_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundcalibration',
            name='background_file',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='backgroundcalibration',
            name='background_image_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='camera',
            name='resolution',
            field=models.CharField(blank=True, default='', help_text='Opcjonalnie: rozdzielczość w zapytaniu (?resolution=...). Puste = bez parametru.', max_length=20),
        ),
    ]
