# Generated by Django 5.2.9 on 2026-02-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0003_background_file_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeltraining',
            name='current_epoch',
            field=models.IntegerField(blank=True, help_text='Current epoch during training', null=True),
        ),
        migrations.AddField(
            model_name='modeltraining',
            name='progress_percent',
            field=models.IntegerField(blank=True, help_text='Training progress 0-100', null=True),
        ),
    ]
