# Generated by Django 4.2.29 on 2026-03-13 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("factory", "0004_add_training_progress_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="backgroundcalibration",
            name="background_images_directory",
            field=models.CharField(
                blank=True,
                help_text="Ścieżka do katalogu na serwerze ze zdjęciami tła. Wszystkie jpg/png z katalogu będą użyte do kalibracji HSV.",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="camera",
            name="roi_x1",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="camera",
            name="roi_x2",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="camera",
            name="roi_y1",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="camera",
            name="roi_y2",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
