# Generated by Django 4.2.29 on 2026-03-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("factory", "0005_add_background_directory_and_roi"),
    ]

    operations = [
        migrations.AddField(
            model_name="camera",
            name="roi_polygon",
            field=models.JSONField(
                blank=True,
                help_text="Lista punktów [[x,y],[x,y],...] 0–1. Gdy ustawione, ma pierwszeństwo przed prostokątem.",
                null=True,
            ),
        ),
    ]
